image: docker
services:
  - docker:dind

stages:
  - publish
  
publish:
  stage: publish
  except:
    - schedules
  before_script:
    - apk add --no-cache curl
    - apk add --no-cache make

  script:
    - make package
    # - make publish-ci NPM_TOKEN=$NPM_TOKEN

  only:
    refs:
      - master